# Generated by Django 6.0.2 on 2026-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='timeout',
            field=models.IntegerField(null=True),
        ),
    ]
