# Generated by Django 6.0.2 on 2026-02-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.field')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fields', models.ManyToManyField(to='devices.field')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='type_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.typedevice'),
        ),
    ]
