# Generated by Django 6.0.2 on 2026-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_field_messages_typedevice_device_type_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
