# Generated by Django 6.0.2 on 2026-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='measurement_unit',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
    ]
