# Generated by Django 6.0.2 on 2026-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_field_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.FloatField(),
        ),
    ]
