# Generated by Django 6.0.2 on 2026-02-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_message_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=255)),
                ('state', models.FloatField()),
                ('block_related_conditions', models.BooleanField()),
                ('block_on', models.IntegerField()),
                ('last_block', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('related_conditions', models.ManyToManyField(blank=True, related_name='related_devices', to='devices.condition')),
            ],
        ),
    ]
