# Generated by Django 6.0.2 on 2026-02-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.TextField(),
        ),
    ]
