# Generated by Django 6.0.2 on 2026-02-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_condition_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.group'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.TextField()),
                ('state', models.TextField()),
                ('block_related_conditions', models.BooleanField()),
                ('block_on', models.IntegerField()),
                ('last_block', models.DateTimeField(blank=True, null=True)),
                ('related_conditions', models.ManyToManyField(blank=True, related_name='related_devices', to='devices.trigger')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='triggers',
            field=models.ManyToManyField(to='devices.trigger'),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
