# Generated by Django 6.0.2 on 2026-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_group_device_group_trigger_device_triggers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='devices.trigger'),
        ),
    ]
