# Generated by Django 6.0.2 on 2026-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='metadata',
        ),
        migrations.AddField(
            model_name='device',
            name='metafield',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
